language: go
go:
- 1.12.x
before_install:
- chmod +x ./sonar.sh
script:
- make lint
- make test
- ./sonar.sh
after_script:
- make cover
addons:
  apt:
    packages:
      - libsdl2-2.0-8
      - libsdl2-image-2.0-4
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
