language: go
go:
- 1.12.x
before_install:
- |
  sudo apt-get install -y libsdl2{,-image,-mixer,-ttf,-gfx}-dev
  chmod +x ./sonar.sh
script:
- make lint
- make test
- ./sonar.sh
after_script:
- make cover
addons:
  apt:
    update: true
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
