language: go
go:
- 1.12.x
before_install:
# Download, make and install SDL2-2.0.8 (stable)
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
  cd SDL2-2.0.9
  ./configure
  make
  sudo make install
  cd ..
  chmod +x ./sonar.sh
script:
- make lint
- make test
- ./sonar.sh
after_script:
- make cover
addons:
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
