language: go
go:
- 1.12.x
before_install:
- |
  apt update
  apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
  chmod +x ./sonar.sh
script:
- make lint
- make test
- ./sonar.sh
after_script:
- make cover
addons:
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
