language: go
go:
- 1.12.x
before_install:
# Download, make and install SDL2-2.0.8 (stable)
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz
  cd SDL2-2.0.9
  ./configure
  make
  sudo make install
  cd ..
script:
- make lint
- make test
- sonar-scanner -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.java.binaries=.
after_script:
- make cover
addons:
  sonarcloud: true
env:
  global:
  - GO111MODULE=on
  - secure: P5JO+fnWMYbjkvEaCzCnqH0Z7Rg7TW8q4LaQEh5/V8XWwZBSGl1uE51LJEaPuhazOMmv9uCHeCP/EMdGotjR5ZVViV/oinKh10TtdP1MWXAJdCw7KAA7FnRxjya5fEYQqCfq2NkFRWHJ1vTLgvfsaJtT4OPpceDNzkUQc7JPDi5dV7aMABBqLbpdq2LsKuUkCZQYVwojS7JJnDfLfJy0dCCnOOSIxomoKXw04p4dLNrfH6/A7S/a9IqcrhO4yfv09vjbRTMfQrZP/znHwOy4etz7QUvgEsYlBupbvrDwrjWZL6sJmTbbvKchmCWRMjURMjHY51lcdBk/KLbom616rp0wEuxATGhN9HVH4ANit9/VyRQ2UM4qWqeAEhgy79MB/r3S0hFReuPiVO+esVyOXlGJr2tvaxm+eJGFT8JuVbOcjPy0hMWt6EvDvOPD0xHXS89xiQsva+fNHoNO67ta/6gPtuo+41+HuBmdHvGEunBhGaShbBQzVI+JW2Locia2GXfBJo73JWcTM2clRWapuzAPzUU5mvAsheMpQBEvVKNkPsEUWbqdRDgIkTCg1EWYCEPsXHs+Jot9XQcBH/MIUWVHO7akeQdD7694/TdRkWOEBHIqCGLW3EBKOvuVKLpVAiIMW8XlG9QeAgsk1xjj8EbsT4NEJgub0lD40IVNnWc=
  - secure: 1edKsQj+bqdJd6GfhdqhjEdqYaIMqStwH6AF0bTCpPJxA6vqGrEpDFcHzuRCF/o3ka49MBP02wkGyqrS72c2QR9QmczeY4Pd27gR5N62d3+W5ibDy/WbPGz4L1aLmRv1Tg9GRAXnNqpDUwXKF14lU7LY8F+qK//yoko4MU2c60LCTF51+kepHEy//YaCVlBVwi4lqzFZ2+ZU3+QQ2qXJJouRiGx7VVO2KBuZ3ja9Ph8BaPqd2C9PaLfqhypUM4sNI8KpEN7bIJtt83ObPGw+upSuUYbEEKQpaVjNhPzyS4tkHVvBbUEcU996VYhwZI8WMMTz3nZWGSJp1m6vL4kdCIOvHNAp1S5ux5NlYnW6iuG6dvjv4R9y9jylJ6f5zG+eNHlwK3Zwd4A8ztfEuA8Qr8gh0KlQrdWC/QKR1fi8wTnQYonhwHOkXmabbRyeBu2H7EOJjvR5yVcatjRXp5kbkc4nkOnkMHHglnZ0kq4WMMECdppUbjFixU1/XqfNluy/cI5dwE22J9RbVKjbq6sDhmcuxsjviuXBVClPEsuoYC21BaQcRk0iGpagnAfKA77pxqp0eLMwuetl/wzyDdupEEjcGg2NMfxLb3cYR7Mpmz3hswKeS70K3KiZ7kXk++uBRmb/vaztxoV1ZbiFOHaPui9z5NsoUxzfkODdIKCL19g=
  - secure: BYLjoMEbXanvhxlsiyT4BS/Xj4semATC0mG3Hz/F0fA+Z/qWrKTYIz1xoUcW+xMud0kYJfDxzhzbl0/QV/7bn9xL2oaA5rkGISlrF/AzVDrUF2qq31DH6U2TT22jQlXjMBH6yzg7+WWTxopIhau+EN1732M2QYXniEfB1WtBhvkj+zW7orMDNfRfUXBQckAnXUNZYcNxdfMDfXI/esWRnCiMZ5AvWu/AyVTgtrYPIKvFwlxqP6hkKxyrH/p5WSD925dLvBsIq1Tc7Zy6UYJKThkcJReo/MXDkG8fQ///tFfqs2SiwM9/pylGss67PTQtOsvAQAr6P0WpBQdotCIiLdUaGTYwT9b+UtEM9wMlopQRnFXYYFk330eFQsl9cV0vHN4bN271OdTuTpR3rKhgKtI0VzcEO6Ut0dWk/96b0lOGWNpujGIX/4Uu3i1ejCg8iVVOn4oiyc0IZH8FVWEQl4RIwc3rFArT9GyOi0wrs0xO2PHz9yxfTnYL6elRVuwm05LLwFkdm8vcZQCn0enPB9ZshbFjsqOvBwZNEGd3jZY2/ZrY7GPAREPWL1gZnoxppIG6t5M365bX4X8gMhDAtdUyeLzzT8hVZ8kFjaTyEh9P2Lca6iZSebHyolqH1A8gL9vgAwMgCcNxuSxJtr4kPpjFR2SEyIs5XH6uYh+h+mc=
